
name: CI/CD for React Application

on:
  push:
    branches:
      - Staging
  pull_request:
    branches:
      - Staging

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build 
        run: |
          npm run build 
  deploy-to-dockerhub:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
              docker build -t acha/cft:v1 . 
      - name: Push image to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          repository: acha30/ghislain_profile
          tags: acha30/ghislain_profile:${{ github.sha }}
      - name: Deploy to UAT
        if: success()
        run: |
          git checkout UAT
          git fetch origin
          git merge --no-ff Staging
          git push origin UAT
      
